/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class setupandroidcomm_xun_com_setupandroidcomm_utils_Security */

#ifndef _Included_setupandroidcomm_xun_com_setupandroidcomm_utils_Security
#define _Included_setupandroidcomm_xun_com_setupandroidcomm_utils_Security
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     setupandroidcomm_xun_com_setupandroidcomm_utils_Security
 * Method:    getSecret
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_setupandroidcomm_xun_com_setupandroidcomm_utils_Security_getSecret
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
